Repository cap4053-cheeky-pixels/EmbodyGame, pull requests merged in 2019-02, with the labels that each got.

#33 Laser projectile variant + basic laser weapon
  Assets/Prefabs/Weapons/BasicLaserWeapon.prefab
  Assets/Prefabs/Weapons/BasicLaserWeapon.prefab.meta
  Assets/Prefabs/Weapons/Projectiles/LaserProjectile.prefab
  Assets/Prefabs/Weapons/Projectiles/LaserProjectile.prefab.meta
  Assets/Scenes/SandboxScenes/AleksandrSandbox.unity
  Assets/Scripts/Entity/Player/Player.cs
  Assets/Scripts/Environmental/Room/RoomScript.cs
  Assets/Scripts/Weapons/BasicLaserWeapon.cs
  Assets/Scripts/Weapons/BasicLaserWeapon.cs.meta
  Assets/Scripts/Weapons/BasicWeapon.cs
Labels: B feature

#42 Code refactoring
  Assets/Prefabs/Weapons/BasicLaserWeapon.prefab
  Assets/Prefabs/Weapons/BasicWeapon.prefab
  Assets/Prefabs/Weapons/Projectiles/BasicProjectile.prefab
  Assets/Prefabs/Weapons/QuadshotWeapon.prefab
  Assets/Prefabs/Weapons/TripleshotWeapon.prefab
  Assets/Scripts/Entity/Entity.cs
  Assets/Scripts/Entity/Player/Player.cs
  Assets/Scripts/Spawning/SpawnScript.cs
  Assets/Scripts/Weapons/BasicLaserWeapon.cs
  Assets/Scripts/Weapons/BasicWeapon.cs
  Assets/Scripts/Weapons/IWeapon.cs
  Assets/Scripts/Weapons/ProjectileWeapon.cs
  Assets/Scripts/Weapons/ProjectileWeapon.cs.meta
  Assets/Scripts/Weapons/QuadshotWeapon.cs
  Assets/Scripts/Weapons/TripleshotWeapon.cs
  Assets/Scripts/Weapons/Weapon.cs
  Assets/Scripts/Weapons/Weapon.cs.meta
Labels: enhancement

#41 Collision damage and invulnerability frames
  Assets/Prefabs/Enemy/BasicEnemy.prefab
  Assets/Prefabs/Enemy/WanderEnemy.prefab
  Assets/Prefabs/Player/MainPlayer.prefab
  Assets/Scenes/SandboxScenes/AleksandrSandbox.meta
  Assets/Scenes/SandboxScenes/AleksandrSandbox.unity
  Assets/Scenes/SandboxScenes/AleksandrSandbox/NavMesh.asset
  Assets/Scenes/SandboxScenes/AleksandrSandbox/NavMesh.asset.meta
  Assets/Scripts/Entity/Entity.cs
  Assets/Scripts/Entity/Player/Player.cs
  ProjectSettings/TagManager.asset
Labels: A feature

#40 Feature/shoot controls
  Assets/Prefabs/Entity.meta
  Assets/Prefabs/Entity/Player.prefab
  Assets/Prefabs/Entity/Player.prefab.meta
  Assets/Prefabs/Player/MainPlayer.prefab
  Assets/Scenes/SandboxScenes/JazySandbox.unity
  Assets/Scripts/Entity/Entity.cs
  Assets/Scripts/Entity/Player/InputController.cs
  Assets/Scripts/Entity/Player/Player.cs
  Assets/Scripts/Entity/Player/ShootController.cs
  Assets/Scripts/Weapons/BasicWeapon.cs
  ProjectSettings/InputManager.asset
  ProjectSettings/ProjectSettings.asset
Labels: A feature

#51 Spike traps
  Assets/Materials/White.mat
  Assets/Materials/White.mat.meta
  Assets/Prefabs/Traps.meta
  Assets/Prefabs/Traps/Spikes.meta
  Assets/Prefabs/Traps/Spikes/Anim.meta
  Assets/Prefabs/Traps/Spikes/Anim/Anim_TrapNeedle_Hide.anim
  Assets/Prefabs/Traps/Spikes/Anim/Anim_TrapNeedle_Hide.anim.meta
  Assets/Prefabs/Traps/Spikes/Anim/Anim_TrapNeedle_Idle.anim
  Assets/Prefabs/Traps/Spikes/Anim/Anim_TrapNeedle_Idle.anim.meta
  Assets/Prefabs/Traps/Spikes/Anim/Anim_TrapNeedle_Play.anim
  Assets/Prefabs/Traps/Spikes/Anim/Anim_TrapNeedle_Play.anim.meta
  Assets/Prefabs/Traps/Spikes/Anim/Anim_TrapNeedle_Show.anim
  Assets/Prefabs/Traps/Spikes/Anim/Anim_TrapNeedle_Show.anim.meta
  Assets/Prefabs/Traps/Spikes/Materials.meta
  Assets/Prefabs/Traps/Spikes/Materials/Tex_DungeonTrap.mat
  Assets/Prefabs/Traps/Spikes/Materials/Tex_DungeonTrap.mat.meta
  Assets/Prefabs/Traps/Spikes/Materials/Tex_DungeonTrap.png
  Assets/Prefabs/Traps/Spikes/Materials/Tex_DungeonTrap.png.meta
  Assets/Prefabs/Traps/Spikes/Prefab.meta
  Assets/Prefabs/Traps/Spikes/Prefab/SpikeTrap.prefab
  Assets/Prefabs/Traps/Spikes/Prefab/SpikeTrap.prefab.meta
  Assets/Prefabs/Traps/Spikes/SpikeTrap.FBX
  Assets/Prefabs/Traps/Spikes/SpikeTrap.FBX.meta
  Assets/Scenes/SandboxScenes/AleksandrSandbox.unity
  README.md
Labels: A feature

#54 Fix invisibility timing bug
  Assets/Scripts/Entity/Player/Player.cs
Labels: bug

#36 Animated menu torches
  Assets/Animations/Torch.anim
  Assets/Animations/Torch.anim.meta
  Assets/Animations/Torch.controller
  Assets/Animations/Torch.controller.meta
  Assets/Scenes/Official/Menu.unity
  Assets/Sprites/animated_torch.png
  Assets/Sprites/animated_torch.png.meta
  README.md
Labels: C feature

#53 Remove fireweapon logic from the player/entity
  Assets/Prefabs/Player/MainPlayer.prefab
  Assets/Scenes/SandboxScenes/JazySandbox.unity
  Assets/Scripts/Entity/Enemy/Enemy.cs
  Assets/Scripts/Entity/Entity.cs
  Assets/Scripts/Entity/Player/IWeaponController.cs
  Assets/Scripts/Entity/Player/IWeaponController.cs.meta
  Assets/Scripts/Entity/Player/Player.cs
  Assets/Scripts/Entity/Player/ShootController.cs
Labels: A feature, enhancement

#59 Boss work in progress
  Assets/Prefabs/Enemy/Devil.meta
  Assets/Prefabs/Enemy/Devil/Animations.meta
  Assets/Prefabs/Enemy/Devil/Animations/DevilAnimationController.controller
  Assets/Prefabs/Enemy/Devil/Animations/DevilAnimationController.controller.meta
  Assets/Prefabs/Enemy/Devil/Animations/Materials.meta
  Assets/Prefabs/Enemy/Devil/Animations/Materials/Devil_texture.mat
  Assets/Prefabs/Enemy/Devil/Animations/Materials/Devil_texture.mat.meta
  Assets/Prefabs/Enemy/Devil/Animations/Materials/hell_new.mat
  Assets/Prefabs/Enemy/Devil/Animations/Materials/hell_new.mat.meta
  Assets/Prefabs/Enemy/Devil/Animations/Materials/hell_texture_1.mat
  Assets/Prefabs/Enemy/Devil/Animations/Materials/hell_texture_1.mat.meta
  Assets/Prefabs/Enemy/Devil/Animations/devil@attack_1.fbx
  Assets/Prefabs/Enemy/Devil/Animations/devil@attack_1.fbx.meta
  Assets/Prefabs/Enemy/Devil/Animations/devil@attack_2.fbx
  Assets/Prefabs/Enemy/Devil/Animations/devil@attack_2.fbx.meta
  Assets/Prefabs/Enemy/Devil/Animations/devil@damage.fbx
  Assets/Prefabs/Enemy/Devil/Animations/devil@damage.fbx.meta
  Assets/Prefabs/Enemy/Devil/Animations/devil@death.fbx
  Assets/Prefabs/Enemy/Devil/Animations/devil@death.fbx.meta
  Assets/Prefabs/Enemy/Devil/Animations/devil@fly.fbx
  Assets/Prefabs/Enemy/Devil/Animations/devil@fly.fbx.meta
  Assets/Prefabs/Enemy/Devil/Animations/devil@idle.fbx
  Assets/Prefabs/Enemy/Devil/Animations/devil@idle.fbx.meta
  Assets/Prefabs/Enemy/Devil/Animations/devil@pose.fbx
  Assets/Prefabs/Enemy/Devil/Animations/devil@pose.fbx.meta
  Assets/Prefabs/Enemy/Devil/Animations/devil@stun.fbx
  Assets/Prefabs/Enemy/Devil/Animations/devil@stun.fbx.meta
  Assets/Prefabs/Enemy/Devil/Animations/devil@victory.fbx
  Assets/Prefabs/Enemy/Devil/Animations/devil@victory.fbx.meta
  Assets/Prefabs/Enemy/Devil/Devil.prefab
  Assets/Prefabs/Enemy/Devil/Devil.prefab.meta
  Assets/Prefabs/Enemy/Devil/Texture.meta
  Assets/Prefabs/Enemy/Devil/Texture/hell_texture_1.png
  Assets/Prefabs/Enemy/Devil/Texture/hell_texture_1.png.meta
  Assets/Prefabs/UI/BossHealth.prefab
  Assets/Prefabs/UI/BossHealth.prefab.meta
  Assets/Prefabs/UI/HUD.prefab
  Assets/Scenes/SandboxScenes/AleksandrSandbox.unity
  Assets/Scenes/SandboxScenes/BossTest.meta
  Assets/Scenes/SandboxScenes/BossTest/NavMesh.asset
  Assets/Scenes/SandboxScenes/BossTest/NavMesh.asset.meta
  Assets/Scripts/Entity/Enemy/Boss.meta
  Assets/Scripts/Entity/Enemy/Boss/DevilAnimationTest.cs
  Assets/Scripts/Entity/Enemy/Boss/DevilAnimationTest.cs.meta
  Assets/Scripts/Entity/Enemy/Boss/DevilBoss.cs
  Assets/Scripts/Entity/Enemy/Boss/DevilBoss.cs.meta
  Assets/Scripts/Entity/Enemy/Boss/FlyBehavior.cs
  Assets/Scripts/Entity/Enemy/Boss/FlyBehavior.cs.meta
  Assets/Scripts/Entity/Enemy/Enemy.cs
  Assets/Scripts/Entity/Player/Player.cs
  Assets/Scripts/Environmental/UI/BossHealth.cs
  Assets/Scripts/Environmental/UI/BossHealth.cs.meta
  Assets/Sprites/BossLifebarRectangle.png
  Assets/Sprites/BossLifebarRectangle.png.meta
  ProjectSettings/QualitySettings.asset
  ProjectSettings/UnityConnectSettings.asset
  assets/Scenes/SandboxScenes/BossTest.unity
  assets/Scenes/SandboxScenes/BossTest.unity.meta
Labels: A feature
