Repository cap4053-cheeky-pixels/EmbodyGame, pull requests merged in 2019-04, with the labels that each got.

#145 Selectively hidden cursor
  Assets/Scripts/CursorManager.cs
  Assets/Scripts/CursorManager.cs.meta
  Assets/Scripts/GameManager.cs
  Assets/Scripts/Menus/LevelIntro.cs
Labels: enhancement

#146 Enemies wait once they arrive at their destination (Wandering)
  Assets/Scripts/Entity/Enemy/MovementBehaviors/WanderMovement.cs
Labels: enhancement

#144 Fix tenti enemy teleportation bug
  Assets/Prefabs/Enemy/TentiEnemy.prefab
Labels: bug-fix

#159 Rapid heart blinking bug fix
  Assets/Scripts/Environmental/UI/HeartSystem.cs
Labels: bug-fix

#152 README game screenshots
  README.md
  Screenshots/ExampleRoom.PNG
  Screenshots/Possession.PNG
  Screenshots/Satan.PNG
Labels: enhancement

#154 Tenticle enemy view range extended
  Assets/Prefabs/Enemy/TentiEnemy.prefab
  Assets/Prefabs/Enemy/TentiEnemyBurst.prefab
Labels: bug-fix

#169 Hotfix/increase enemy healths
  Assets/Prefabs/Enemy/CruzEnemy.prefab
  Assets/Prefabs/Enemy/CubexEnemy.prefab
  Assets/Prefabs/Enemy/Devil/Devil.prefab
  Assets/Prefabs/Enemy/KatEnemy.prefab
  Assets/Prefabs/Enemy/TentiEnemy.prefab
  Assets/Prefabs/Player/MainPlayer.prefab
  Assets/Scenes/Official/Level1.unity
  Assets/Scripts/Weapons/Weapon.cs
Labels: C feature

#172 Hotfix/heavy hearts
  Assets/Prefabs/Enemy/CruzEnemy.prefab
  Assets/Prefabs/Enemy/CubexEnemy.prefab
  Assets/Prefabs/Enemy/KatEnemy.prefab
  Assets/Prefabs/Enemy/TentiEnemy.prefab
  Assets/Prefabs/Enemy/TentiEnemyBurst.prefab
  Assets/Scripts/HeartPusher.cs
  Assets/Scripts/HeartPusher.cs.meta
Labels: C feature, bug-fix

#167 Hotfix meteor spawn
  Assets/PyroParticles/Prefab/Prefab/MeteorSwarm.prefab
  Assets/Scripts/Entity/Enemy/Boss/PhaseTwo.cs
Labels: bug-fix

#168 Hotfix: bug with automatic pause menu navigation
  Assets/Prefabs/GameManager.prefab
Labels: bug-fix

#161 Feature/random spawns
  Assets/Prefabs/Room/SpawnPoint.prefab
  Assets/Scenes/Official/Level1.unity
  Assets/Scripts/Spawning/SpawnPoint.cs
  Assets/Scripts/Spawning/Spawner.cs
Labels: C feature, enhancement

#182 Door bug fix
  Assets/Scripts/Environmental/Room/RoomScript.cs
Labels: bug-fix

#176 Feature/final sounds
  Assets/Audio/Sound Effects/cruzdeath.wav
  Assets/Audio/Sound Effects/cruzdeath.wav.meta
  Assets/Audio/basicweapon_fire.wav
  Assets/Audio/basicweapon_fire.wav.meta
  Assets/Audio/possession.wav
  Assets/Audio/possession.wav.meta
  Assets/Prefabs/.DS_Store
  Assets/Prefabs/Enemy/CruzEnemy.prefab
  Assets/Prefabs/Enemy/CubexEnemy.prefab
  Assets/Prefabs/Enemy/KatEnemy.prefab
  Assets/Prefabs/Enemy/TentiEnemy.prefab
  Assets/Prefabs/Enemy/TentiEnemyBurst.prefab
  Assets/Prefabs/Player/MainPlayer.prefab
  Assets/Prefabs/Weapons/BasicWeapon.prefab
  Assets/Prefabs/Weapons/TripleshotWeapon.prefab
  Assets/Scripts/Entity/Enemy/Enemy.cs
  Assets/Scripts/Entity/Entity.cs
  Assets/Scripts/Entity/Player/Player.cs
Labels: C feature

#184 Hotfix/possession heartdrops fix2 (Alternative)
  Assets/Prefabs/Hearts/Gold-Heart.prefab
  Assets/Prefabs/Hearts/Half-Gold-Heart.prefab
  Assets/Prefabs/Hearts/Half-Heart.prefab
  ProjectSettings/DynamicsManager.asset
  ProjectSettings/TagManager.asset
Labels: B feature, bug-fix

#186 Hotfix: boss death audio
  Assets/Prefabs/Enemy/Devil/Devil.prefab
  Assets/Scripts/Entity/Enemy/Boss/Boss.cs
  Assets/Scripts/Entity/Enemy/Boss/DevilBoss.cs
  Assets/Scripts/Entity/Enemy/Enemy.cs
  Assets/Scripts/Entity/Entity.cs
  Assets/Scripts/Entity/Player/Player.cs
Labels: bug-fix
