Repository cap4053-cheeky-pixels/EmbodyGame, pull requests merged in 2019-03, with the labels that each got.

#64 Added actual files i forgot to stage
  .DS_Store
  Assets/.DS_Store
  Assets/Prefabs/TrapDoor.prefab
  Assets/Prefabs/TrapDoor.prefab.meta
  Assets/Scenes/SandboxScenes/HingeRight.anim
  Assets/Scenes/SandboxScenes/HingeRight.anim.meta
  Assets/Scenes/SandboxScenes/LeftAnim.anim
  Assets/Scenes/SandboxScenes/LeftAnim.anim.meta
  Assets/Scenes/SandboxScenes/TrapDoor.unity
  Assets/Scenes/SandboxScenes/TrapDoor.unity.meta
  Assets/Scripts/.DS_Store
  Assets/Scripts/Entity/.DS_Store
  Assets/Scripts/TrapDoorOpen.cs
  Assets/Scripts/TrapDoorOpen.cs.meta
Labels: A feature

#69 Feature/new basic enemy
  Assets/Prefabs/Enemy/CubexEnemy.prefab
  Assets/Prefabs/Enemy/CubexEnemy.prefab.meta
  Assets/Prefabs/Models/CubexEnemy.fbx
  Assets/Prefabs/Models/CubexEnemy.fbx.meta
  Assets/Prefabs/Models/Materials.meta
  Assets/Prefabs/Models/Materials/Cubex.png
  Assets/Prefabs/Models/Materials/Cubex.png.meta
  Assets/Prefabs/Models/Materials/Diffuse.mat
  Assets/Prefabs/Models/Materials/Diffuse.mat.meta
  Assets/Prefabs/Models/Materials/Diffuse.png
  Assets/Prefabs/Models/Materials/Diffuse.png.meta
  Assets/Prefabs/Models/Materials/Diffuse.psd.meta
  Assets/Prefabs/Models/Materials/ambient.png.meta
  Assets/Prefabs/Player/Slippery.physicMaterial
  Assets/Scenes/SandboxScenes/JazySandbox.unity
  Assets/Scripts/Entity/Enemy/CubexAnimationController.controller
  Assets/Scripts/Entity/Enemy/CubexAnimationController.controller.meta
  Assets/Scripts/Entity/Enemy/SimpleAnimatorController.cs
  Assets/Scripts/Entity/Enemy/SimpleAnimatorController.cs.meta
  Assets/Scripts/Entity/Enemy/SimpleNMAAnimatorController.cs
  Assets/Scripts/Entity/Enemy/SimpleNMAAnimatorController.cs.meta
Labels: A feature

#68 Feature/projectile particles
  Assets/Prefabs/Weapons/Projectiles/BasicProjectile.prefab
  Assets/Prefabs/Weapons/Projectiles/LaserProjectile.prefab
  Assets/Scenes/SandboxScenes/JazySandbox.unity
  Assets/Scenes/SandboxScenes/JazySandboxStuffs/DummyRoomController.cs
  Assets/Scripts/Weapons/Projectile.meta
  Assets/Scripts/Weapons/Projectile/ParticlePieceLight.prefab
  Assets/Scripts/Weapons/Projectile/ParticlePieceLight.prefab.meta
  Assets/Scripts/Weapons/Projectile/Projectile.cs
  Assets/Scripts/Weapons/Projectile/Projectile.cs.meta
  Assets/Scripts/Weapons/Projectile/ProjectileHitEffect.cs
  Assets/Scripts/Weapons/Projectile/ProjectileHitEffect.cs.meta
  Assets/Scripts/Weapons/Projectile/ProjectileHitParticles.prefab
  Assets/Scripts/Weapons/Projectile/ProjectileHitParticles.prefab.meta
  Packages/manifest.json
Labels: B feature

#70 Official Level 1, Wall and Floor Textures, and Critical Health Feedback
  Assets/Audio/DevilPhaseTwoAudio.ogg
  Assets/Audio/DevilPhaseTwoAudio.ogg.meta
  Assets/Prefabs/Enemy/Devil/Animations/DevilAnimationController.controller
  Assets/Prefabs/Enemy/Devil/Devil.prefab
  Assets/Prefabs/Enemy/Devil/DevilFlames.prefab
  Assets/Prefabs/Enemy/Devil/DevilFlames.prefab.meta
  Assets/Prefabs/Player/MainPlayer.prefab
  Assets/Prefabs/Room/HoriWallWithDoor.prefab
  Assets/Prefabs/Room/HoriWallWithoutDoor.prefab
  Assets/Prefabs/Room/Room.prefab
  Assets/Prefabs/Room/VertWallWithDoor.prefab
  Assets/Prefabs/Room/VertWallWithoutDoor.prefab
  Assets/Prefabs/UI/LifeBar.prefab
  Assets/Scenes/Official/Level1.meta
  Assets/Scenes/Official/Level1.unity
  Assets/Scenes/Official/Level1.unity.meta
  Assets/Scenes/Official/Level1/NavMesh.asset
  Assets/Scenes/Official/Level1/NavMesh.asset.meta
  Assets/Scripts/Entity/Enemy/Boss/DevilBoss.cs
  Assets/Scripts/Entity/Enemy/Boss/PhaseTwo.cs
  Assets/Scripts/Entity/Enemy/Boss/PhaseTwo.cs.meta
  Assets/Scripts/Entity/Enemy/Enemy.cs
  Assets/Scripts/Entity/Player/Player.cs
  Assets/Scripts/Environmental/Room/RoomScript.cs
  Assets/Scripts/Environmental/UI/HeartSystem.cs
  Assets/Sprites/Blood Stone CH16.png
  Assets/Sprites/Blood Stone CH16.png.meta
  Assets/Sprites/Lava.png
  Assets/Sprites/Lava.png.meta
  Assets/Sprites/Materials.meta
  Assets/Sprites/Materials/Blood Stone CH16.mat
  Assets/Sprites/Materials/Blood Stone CH16.mat.meta
  Assets/Sprites/Materials/Lava.mat
  Assets/Sprites/Materials/Lava.mat.meta
  Assets/Sprites/Materials/Mine Rocks CH16.mat
  Assets/Sprites/Materials/Mine Rocks CH16.mat.meta
  Assets/Sprites/Mine Rocks CH16.png
  Assets/Sprites/Mine Rocks CH16.png.meta
  README.md
Labels: A feature

#58 Heart drops sandbox
  Assets/Prefabs/Half-Heart.prefab
  Assets/Prefabs/Half-Heart.prefab.meta
  Assets/Prefabs/Heart.prefab
  Assets/Prefabs/Heart.prefab.meta
  Assets/Scenes/SandboxScenes/CameranSandbox.unity
  Assets/Scenes/SandboxScenes/CameranSandbox.unity.meta
  Assets/Scripts/Entity/Enemy/Enemy.cs
  Assets/Scripts/Entity/Enemy/EnemyDrop.cs
  Assets/Scripts/Entity/Enemy/EnemyDrop.cs.meta
  Assets/Scripts/Entity/Enemy/Heart.cs
  Assets/Scripts/Entity/Enemy/Heart.cs.meta
  ProjectSettings/TagManager.asset
Labels: A feature

#80 Spawn mechanic update
  Assets/Audio/GateSound.ogg
  Assets/Audio/GateSound.ogg.meta
  Assets/Prefabs/Room/Gate.prefab
  Assets/Prefabs/Room/Room.prefab
  Assets/Scenes/Official/Level1.unity
  Assets/Scripts/Environmental/Room/RoomScript.cs
  Assets/Scripts/Spawning/SpawnPoint.cs
  Assets/Scripts/Spawning/Spawner.cs
  Assets/Scripts/Spawning/Spawner.cs.meta
  README.md
Labels: A feature, enhancement

#81 Golden heart sprites
  Assets/Sprites/hearts.png
  Assets/Sprites/hearts.png.meta
Labels: enhancement

#90 Toned down meteors and various other arson fixes
  Assets/Prefabs/Enemy/Devil/Devil.prefab
  Assets/Prefabs/Player/MainPlayer.prefab
  Assets/Prefabs/Weapons/Projectiles/Firebolt.prefab
  Assets/PyroParticles/Prefab/Prefab/Meteor.prefab
  Assets/PyroParticles/Prefab/Prefab/MeteorSwarm.prefab
  Assets/PyroParticles/Prefab/Prefab/SmallFires.prefab
  Assets/PyroParticles/Prefab/Prefab/WallOfFire.prefab
  Assets/PyroParticles/Prefab/Script/MeteorSwarmScript.cs
  Assets/Scripts/Entity/Enemy/Boss/PhaseTwo.cs
Labels: A feature, enhancement

#88 Menu improvements, scene fading, and pre-level message generator
  Assets/Animations/SceneFadeController.controller
  Assets/Animations/SceneFadeController.controller.meta
  Assets/Animations/SceneFadeIn.anim
  Assets/Animations/SceneFadeIn.anim.meta
  Assets/Audio/DramaticSound.ogg
  Assets/Audio/DramaticSound.ogg.meta
  Assets/Font.meta
  Assets/Font/ConcertOne-Regular.ttf
  Assets/Font/ConcertOne-Regular.ttf.meta
  Assets/Prefabs/Menu/Button.prefab
  Assets/Prefabs/UI/SceneFader.prefab
  Assets/Prefabs/UI/SceneFader.prefab.meta
  Assets/Scenes/Official/Controls.unity
  Assets/Scenes/Official/Level1.unity
  Assets/Scenes/Official/LevelIntro.unity
  Assets/Scenes/Official/LevelIntro.unity.meta
  Assets/Scenes/Official/Menu.unity
  Assets/Scripts/Menus/LevelIntro.cs
  Assets/Scripts/Menus/LevelIntro.cs.meta
  Assets/Scripts/Menus/LoadSceneOnClick.cs
  Assets/Scripts/Menus/MenuMusic.cs
  ProjectSettings/EditorBuildSettings.asset
  README.md
Labels: enhancement

#92 Golden hearts probabilities
  Assets/Prefabs/Enemy/BasicEnemy.prefab
  Assets/Prefabs/Enemy/CubexEnemy.prefab
  Assets/Prefabs/Enemy/KatEnemy.prefab
  Assets/Prefabs/Enemy/WanderEnemy.prefab
  Assets/Prefabs/Gold-Heart.prefab
  Assets/Prefabs/Gold-Heart.prefab.meta
  Assets/Prefabs/Half-Gold-Heart.prefab
  Assets/Prefabs/Half-Gold-Heart.prefab.meta
  Assets/Prefabs/UI/GoldenHealth.prefab
  Assets/Prefabs/UI/GoldenHealth.prefab.meta
  Assets/Prefabs/UI/HUD.prefab
  Assets/Scenes/SandboxScenes/CameranSandbox.unity
  Assets/Scripts/Entity/Enemy/EnemyDrop.cs
  Assets/Scripts/Entity/Enemy/Heart.cs
  Assets/Scripts/Entity/Player/Player.cs
  Assets/Scripts/Environmental/UI/GoldHeartSystem.cs
  Assets/Scripts/Environmental/UI/GoldHeartSystem.cs.meta
Labels: A feature

#89 Enemy spawn delay
  Assets/Audio/SpawnAudio.ogg
  Assets/Audio/SpawnAudio.ogg.meta
  Assets/Prefabs/Enemy/Devil/Devil.prefab
  Assets/Prefabs/Room/Room.prefab
  Assets/Prefabs/Room/SpawnPoint.prefab
  Assets/Prefabs/Room/Spawner.prefab
  Assets/Prefabs/Room/Spawner.prefab.meta
  Assets/Scenes/Official/Level1.unity
  Assets/Scripts/Environmental/Room/RoomScript.cs
  Assets/Scripts/Spawning/Spawner.cs
  README.md
Labels: A feature, enhancement

#93 Pause menu
  Assets/Prefabs/Menu/PauseMenu.prefab
  Assets/Prefabs/Menu/PauseMenu.prefab.meta
  Assets/Scripts/Menus/LevelIntro.cs
  Assets/Scripts/Menus/PauseMenu.cs
  Assets/Scripts/Menus/PauseMenu.cs.meta
Labels: A feature

#95 Feature/more enemies
  Assets/Animations/CruzAnimationController.controller
  Assets/Animations/CruzAnimationController.controller.meta
  Assets/Animations/CubexAnimationController.controller
  Assets/Animations/CubexAnimationController.controller.meta
  Assets/Animations/KatAnimationController.controller
  Assets/Animations/KatAnimationController.controller.meta
  Assets/Animations/TentiAnimationController.controller
  Assets/Animations/TentiAnimationController.controller.meta
  Assets/Prefabs/Enemy/CruzEnemy.prefab
  Assets/Prefabs/Enemy/CruzEnemy.prefab.meta
  Assets/Prefabs/Enemy/TentiEnemy.prefab
  Assets/Prefabs/Enemy/TentiEnemy.prefab.meta
  Assets/Prefabs/Models/CruzModel.meta
  Assets/Prefabs/Models/CruzModel/CruzModel.fbx
  Assets/Prefabs/Models/CruzModel/CruzModel.fbx.meta
  Assets/Prefabs/Models/CruzModel/Textures.meta
  Assets/Prefabs/Models/CruzModel/Textures/CruxTexture.png
  Assets/Prefabs/Models/CruzModel/Textures/CruxTexture.png.meta
  Assets/Prefabs/Models/CruzModel/Textures/CruzNormalMap.png
  Assets/Prefabs/Models/CruzModel/Textures/CruzNormalMap.png.meta
  Assets/Prefabs/Models/CruzModel/Textures/Material.001.mat
  Assets/Prefabs/Models/CruzModel/Textures/Material.001.mat.meta
  Assets/Prefabs/Models/TentiModel.meta
  Assets/Prefabs/Models/TentiModel/TentiMaterial.mat
  Assets/Prefabs/Models/TentiModel/TentiMaterial.mat.meta
  Assets/Prefabs/Models/TentiModel/TentiModel.fbx
  Assets/Prefabs/Models/TentiModel/TentiModel.fbx.meta
  Assets/Prefabs/Models/TentiModel/TentiNormal.png
  Assets/Prefabs/Models/TentiModel/TentiNormal.png.meta
  Assets/Prefabs/Models/TentiModel/TentiTexture.png
  Assets/Prefabs/Models/TentiModel/TentiTexture.png.meta
  Assets/Prefabs/Player/MainPlayer.prefab
  Assets/Scenes/SandboxScenes/JazySandbox.unity
  Assets/Scripts/Entity/Enemy/DeathAnimatorController.cs
  Assets/Scripts/Entity/Enemy/DeathAnimatorController.cs.meta
  Assets/Scripts/Entity/Enemy/Enemy.cs
  Assets/Scripts/Entity/Enemy/IOnPossessionController.cs
  Assets/Scripts/Entity/Enemy/IOnPossessionController.cs.meta
  Assets/Scripts/Entity/Enemy/MovementBehaviors/TurretEnemyNonMovement.cs
  Assets/Scripts/Entity/Enemy/MovementBehaviors/TurretEnemyNonMovement.cs.meta
  Assets/Scripts/Entity/Enemy/SimpleNMAAnimatorController.cs
  Assets/Scripts/Entity/Enemy/SimpleRBAnimatorController.cs
  Assets/Scripts/Entity/Enemy/SimpleRBAnimatorController.cs.meta
  Assets/Scripts/Entity/Entity.cs
  Assets/Scripts/Entity/Player/Player.cs
  Assets/Scripts/Entity/Player/Possession.cs
Labels: A feature

#96 Heart consumption audio + pause menu stretch fix
  Assets/Audio/GoldenHeartPickupSound.ogg
  Assets/Audio/GoldenHeartPickupSound.ogg.meta
  Assets/Audio/HeartPickupSound.ogg
  Assets/Audio/HeartPickupSound.ogg.meta
  Assets/Prefabs/Gold-Heart.prefab
  Assets/Prefabs/Half-Gold-Heart.prefab
  Assets/Prefabs/Half-Heart.prefab
  Assets/Prefabs/Heart.prefab
  Assets/Prefabs/Menu/PauseMenu.prefab
  Assets/Scripts/Entity/Enemy/Heart.cs
  README.md
Labels: enhancement

#98 Remove player movement dependancy on framerate
  Assets/Materials/PlayeraFallingSkybox.mat
  Assets/Scripts/Entity/Player/PlayerMovement.cs
Labels: bug-fix

#106 Fix boss health race condition
  Assets/Scripts/Environmental/UI/BossHealth.cs
Labels: bug-fix

#109 Fix issue where restart would break the boss battle.
  Assets/Scripts/Environmental/UI/BossHealth.cs
  Assets/Scripts/GameManager.cs
Labels: bug-fix

#112 Fix bug where the player wouldnt animate after possess
  Assets/Scripts/Entity/Player/Possession.cs
Labels: bug-fix

#123 Wandering Behavior + Field of View/Player Detection
  Assets/Editor.meta
  Assets/Prefabs/Enemy/CruzEnemy.prefab
  Assets/Prefabs/Enemy/CubexEnemy.prefab
  Assets/Prefabs/Enemy/KatEnemy.prefab
  Assets/Prefabs/Enemy/TentiEnemy.prefab
  Assets/Prefabs/Enemy/TentiEnemyBurst.prefab
  Assets/Prefabs/Hearts.meta
  Assets/Prefabs/Hearts/Gold-Heart.prefab
  Assets/Prefabs/Hearts/Gold-Heart.prefab.meta
  Assets/Prefabs/Hearts/Half-Gold-Heart.prefab
  Assets/Prefabs/Hearts/Half-Gold-Heart.prefab.meta
  Assets/Prefabs/Hearts/Half-Heart.prefab
  Assets/Prefabs/Hearts/Half-Heart.prefab.meta
  Assets/Prefabs/Hearts/Heart.prefab
  Assets/Prefabs/Hearts/Heart.prefab.meta
  Assets/Prefabs/Player/MainPlayer.prefab
  Assets/Prefabs/Possession.meta
  Assets/Prefabs/Possession/Halo.prefab
  Assets/Prefabs/Possession/Halo.prefab.meta
  Assets/Prefabs/Traps/Rock/Rock.prefab
  Assets/Prefabs/Traps/TrapDoor.prefab
  Assets/Prefabs/Traps/TrapDoor.prefab.meta
  Assets/Scenes/Official/Level1.unity
  Assets/Scenes/Official/Level1/NavMesh.asset
  Assets/Scripts/Entity/Enemy/AIAttackController.cs
  Assets/Scripts/Entity/Enemy/Controllers.meta
  Assets/Scripts/Entity/Enemy/Controllers/AIAttackController.cs
  Assets/Scripts/Entity/Enemy/Controllers/AIAttackController.cs.meta
  Assets/Scripts/Entity/Enemy/Controllers/DeathAnimatorController.cs
  Assets/Scripts/Entity/Enemy/Controllers/DeathAnimatorController.cs.meta
  Assets/Scripts/Entity/Enemy/Controllers/IOnDeathController.cs
  Assets/Scripts/Entity/Enemy/Controllers/IOnDeathController.cs.meta
  Assets/Scripts/Entity/Enemy/Controllers/IOnPossessionController.cs
  Assets/Scripts/Entity/Enemy/Controllers/IOnPossessionController.cs.meta
  Assets/Scripts/Entity/Enemy/Controllers/SimpleNMAAnimatorController.cs
  Assets/Scripts/Entity/Enemy/Controllers/SimpleNMAAnimatorController.cs.meta
  Assets/Scripts/Entity/Enemy/Controllers/SimpleRBAnimatorController.cs
  Assets/Scripts/Entity/Enemy/Controllers/SimpleRBAnimatorController.cs.meta
  Assets/Scripts/Entity/Enemy/DetectPlayer.cs
  Assets/Scripts/Entity/Enemy/DetectPlayer.cs.meta
  Assets/Scripts/Entity/Enemy/FieldOfView.cs
  Assets/Scripts/Entity/Enemy/FieldOfView.cs.meta
  Assets/Scripts/Entity/Enemy/FieldOfViewEditor.cs
  Assets/Scripts/Entity/Enemy/FieldOfViewEditor.cs.meta
  Assets/Scripts/Entity/Enemy/HeartPickups.meta
  Assets/Scripts/Entity/Enemy/HeartPickups/EnemyDrop.cs
  Assets/Scripts/Entity/Enemy/HeartPickups/EnemyDrop.cs.meta
  Assets/Scripts/Entity/Enemy/HeartPickups/Heart.cs
  Assets/Scripts/Entity/Enemy/HeartPickups/Heart.cs.meta
  Assets/Scripts/Entity/Enemy/MovementBehaviors/EnemyMovement.cs
  Assets/Scripts/Entity/Enemy/MovementBehaviors/PursuePlayer.cs
  Assets/Scripts/Entity/Enemy/MovementBehaviors/PursuePlayer.cs.meta
  Assets/Scripts/Entity/Enemy/MovementBehaviors/WanderMovement.cs
  Assets/Scripts/Entity/Enemy/MovementBehaviors/WanderMovement.cs.meta
  ProjectSettings/TagManager.asset
Labels: B feature, enhancement

#128 Code cleanup for various scripts
  Assets/Scripts/Entity/Enemy/DetectPlayer.cs
  Assets/Scripts/Entity/Enemy/Enemy.cs
  Assets/Scripts/Entity/Enemy/MovementBehaviors/WanderMovement.cs
Labels: spaghetti-cleanup

#135 Enemy health event hotfix
  Assets/Scripts/Entity/Enemy/Enemy.cs
Labels: bug-fix

#138 Art for player/build settings
  Assets/Editor/FieldOfViewEditor.cs
  Assets/Editor/FieldOfViewEditor.cs.meta
  Assets/Sprites/Build Art.meta
  Assets/Sprites/Build Art/GameIcon.PNG
  Assets/Sprites/Build Art/GameIcon.PNG.meta
  Assets/Sprites/Build Art/LauncherImage.PNG
  Assets/Sprites/Build Art/LauncherImage.PNG.meta
  Assets/Sprites/Build Art/TeamLogo.png
  Assets/Sprites/Build Art/TeamLogo.png.meta
  Assets/Sprites/Environmental.meta
  Assets/Sprites/Environmental/Blood Stone CH16.png
  Assets/Sprites/Environmental/Blood Stone CH16.png.meta
  Assets/Sprites/Environmental/BossLifebarRectangle.png
  Assets/Sprites/Environmental/BossLifebarRectangle.png.meta
  Assets/Sprites/Environmental/Lava.png
  Assets/Sprites/Environmental/Lava.png.meta
  Assets/Sprites/Environmental/Mine Rocks CH16.png
  Assets/Sprites/Environmental/Mine Rocks CH16.png.meta
  Assets/Sprites/Environmental/hearts.png
  Assets/Sprites/Environmental/hearts.png.meta
  Assets/Sprites/Environmental/star.png
  Assets/Sprites/Environmental/star.png.meta
  Assets/Sprites/Menu.meta
  Assets/Sprites/Menu/TitleScreen.PNG
  Assets/Sprites/Menu/TitleScreen.PNG.meta
  Assets/Sprites/Menu/animated_torch.png
  Assets/Sprites/Menu/animated_torch.png.meta
  ProjectSettings/ProjectSettings.asset
Labels: A feature, enhancement
